import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { Header } from "@/widgets/Header";

import "@/app/styles/global.css";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={roboto.className}>
      <Header />
      {children}
    </body>
  </html>
);

export default RootLayout;
